function createimage(cdata1, Parent1)
%CREATEIMAGE(cdata1, Parent1)
%  CDATA1:  image cdata
%  PARENT1:  image parent

%  Auto-generated by MATLAB on 19-Oct-2020 14:15:39

% Create image
image([116  118 119 120 121 122 123 124 125 126 127 128 129 130 131 132],...
    [244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260],...
    cdata1,'Parent',Parent1,'CDataMapping','scaled');

